# Auth Types
T_LOGIN = "LOGIN"
T_REGISTER = "REGISTER"
T_LOGOUT = "LOGOUT"

# Query Types
T_LIST_ONLINE_USERS = "LIST_ONLINE_USERS"
T_LIST_GAMES = "LIST_GAMES"
T_GET_GAME_DETAIL = "GET_GAME_DETAIL"
T_GAME_REVIEW = "GAME_REVIEW"


# Room Types
T_CREATE_ROOM = "CREATE_ROOM"
T_JOIN_ROOM = "JOIN_ROOM"
T_LEAVE_ROOM = "LEAVE_ROOM"
T_START_GAME = "START_GAME"
T_END_GAME = "END_GAME"
T_LIST_ROOMS = "LIST_ROOMS"
