# Auth Types
T_LOGIN = "LOGIN"
T_REGISTER = "REGISTER"
T_LOGOUT = "LOGOUT"

# Query Types
T_LIST_ONLINE_USERS = "LIST_ONLINE_USERS"
T_LIST_GAMES = "LIST_GAMES"
T_GET_GAME_DETAIL = "GET_GAME_DETAIL"
T_GAME_REVIEW = "GAME_REVIEW"
