# Auth Types
T_LOGIN = "LOGIN"
T_REGISTER = "REGISTER"
T_LOGOUT = "LOGOUT"

# Auth Types
T_DEVELOPER_LOGIN = "DEVELOPER_LOGIN"
T_DEVELOPER_LOGOUT = "DEVELOPER_LOGOUT"
T_DEVELOPER_REGISTER = "DEVELOPER_REGISTER"

# Query Types
T_LIST_ONLINE_USERS = "LIST_ONLINE_USERS"
T_LIST_GAMES = "LIST_GAMES"
T_GET_GAME_DETAIL = "GET_GAME_DETAIL"
T_GAME_REVIEW = "GAME_REVIEW"


# Room Types
T_CREATE_ROOM = "CREATE_ROOM"
T_JOIN_ROOM = "JOIN_ROOM"
T_LEAVE_ROOM = "LEAVE_ROOM"
T_START_GAME = "START_GAME"
T_END_GAME = "END_GAME"
T_LIST_ROOMS = "LIST_ROOMS"

# Developer Types
T_LIST_DEVELOPER_GAMES = "LIST_DEVELOPER_GAMES"
T_UPLOAD_GAME = "UPLOAD_GAME"
T_UPDATE_GAME = "UPDATE_GAME"
T_DELETE_GAME = "DELETE_GAME"

# Chunked Upload Types
T_UPLOAD_GAME_INIT = "UPLOAD_GAME_INIT"
T_UPLOAD_GAME_CHUNK = "UPLOAD_GAME_CHUNK"
T_UPLOAD_GAME_FINISH = "UPLOAD_GAME_FINISH"

# Chunked Update Types
T_UPDATE_GAME_INIT = "UPDATE_GAME_INIT"
T_UPDATE_GAME_CHUNK = "UPDATE_GAME_CHUNK"
T_UPDATE_GAME_FINISH = "UPDATE_GAME_FINISH"

# Download Game Types
T_DOWNLOAD_GAME_INIT = "DOWNLOAD_GAME_INIT"
T_DOWNLOAD_GAME_CHUNK = "DOWNLOAD_GAME_CHUNK"
T_DOWNLOAD_GAME_FINISH = "DOWNLOAD_GAME_FINISH"
